version: "3.8"
services:
  casa:
    container_name: casa
    image: casa/nacos-server:${NACOS_VERSION}
    build:
      context: ../image/nacos/2.3.2/
      dockerfile: ./Dockerfile
    volumes:
      - ./mountpoint/casa/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    env_file:
      - ../env/casa-cluster-ip-singlepoint-nacos.env
    restart: on-failure
