version: "3.8"
services:
  mysql:
    container_name: mysql
    image: casa/mysql-server:5.7
    build:
      context: .
      dockerfile: ../image/mysql/5.7/Dockerfile
    env_file:
      - ../env/casa-cluster-ip-singlepoint-mysql.env
    volumes:
      - ./mountpoint/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
